# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    initCU: docker.io/omecproject/pod-init:1.0.0
    vranL3: registry.aether.opennetworking.org/aether/accelleran-cu-l3-tdd:v1.0.2
    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  pullPolicy: IfNotPresent

nodeSelectors:
  enabled: false
  accelleranCBRSCU:
    label: accelleran-cbrs-cu
    value: enabled

resources:
  enabled: true
  accelleranCBRSCU:
    requests:
      cpu: 3
      memory: 1Gi
    limits:
      cpu: 3
      memory: 1Gi

config:
  vranL3:
    zlogConf:
      bufferMin: 64K
      bufferMax: 64K
    instanceId: onfcell202 # Cell ID -- Unique value for each L2/DU-L3/CU pair, no capital and special character
    tac: 202
    freqBand: 48
    earfcnDl: 55990
    earfcnUl: 55990
    plmnId: "371211" # 130501 for aether If not, 315010 oldone: 371211
    ports:
      s1ap:
        port: 36412
        nodePort: 31412
        protocol: SCTP
  redis:
    ports:
      redisPort:
        port: 6379
  mme:
    ip: 10.90.0.151
    s1apPort: 36412
