apiVersion: v1
kind: ConfigMap
metadata:
  name: xos-core
  labels:
    {{- include "xos-core.release_labels" . | indent 4 }}
data:
  config: |
    name: xos-core
    database:
      name: xos
      username: postgres
      password: password
    logging:
      version: 1
      handlers:
        console:
          class: logging.StreamHandler
        file:
          class: logging.handlers.RotatingFileHandler
          filename: /var/log/xos.log
          maxBytes: 10485760
          backupCount: 5
      loggers:
        '':
          handlers:
              - console
              - file
          level: DEBUG
    xos_dir: /opt/xos
