apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xos-db
  labels:
    app: xos-db    
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xos-db    
      annotations:
        checksum/config-map: {{ include (print $.Chart.Name "/templates/db-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: xos-db 
          image: {{ .Values.pull_docker_registry }}{{ .Values.images.xos_db.repository }}:{{ .Values.images.xos_db.tag }}
          ports:
            - containerPort: 5432 
              protocol: TCP
          env:
            - name: SERVICE_5432_NAME
              valueFrom:
                configMapKeyRef:
                  name: xos-db
                  key: service_5432_name
