---
# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for the COMAC profile.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

images:
  toscaLoader:
    repository: 'xosproject/tosca-loader'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'
  xos_api_tester:
    repository: 'xosproject/xos-api-tester'
    tag: 'master'
    pullPolicy: 'Always'

global:
  registry: ""

xosAdminUser: "admin@opencord.org"
xosAdminPassword: "letmein"

# ONOS applications
sadisAppUrl: "https://oss.sonatype.org/content/groups/public/org/opencord/sadis-app/3.1.0/sadis-app-3.1.0.oar"
sadisAppVersion: "3.1.0"

dhcpl2relayAppUrl: "https://oss.sonatype.org/content/groups/public/org/opencord/dhcpl2relay-app/1.6.0/dhcpl2relay-app-1.6.0.oar"
dhcpl2relayAppVersion: "1.6.0"

oltAppUrl: "https://oss.sonatype.org/content/groups/public/org/opencord/olt-app/3.0.1/olt-app-3.0.1.oar"
oltAppVersion: "3.0.1"

kafkaAppUrl: "https://oss.sonatype.org/content/groups/public/org/opencord/kafka/1.1.0/kafka-1.1.0.oar"
kafkaAppVersion: "1.1.0"

onosRestService: "onos-ui.default.svc.cluster.local"
kafkaService: "cord-kafka.default.svc.cluster.local:9092"

aaaAppUrl: "https://oss.sonatype.org/content/groups/public/org/opencord/aaa-app/1.9.0/aaa-app-1.9.0.oar"
aaaAppVersion: "1.9.0"

att-workflow-driver:
  kafkaService: "cord-platform-kafka"

resdentialService:
  enabled: false

# whether to install or not this shared services
vrouter:
  enabled: true
fabric:
  enabled: true
onos-service:
  enabled: true
